export enum PaymentStatus {
    PAID = 'PAID',
    FAILED = 'FAILED',
    REFUND_PENDING = 'REFUND_PENDING',
    REFUND_PROCESSING = 'REFUND_PROCESSING',
    REFUND = 'REFUND',
}

export enum PaymentSort {
    NEWEST = 'NEWEST',
    OLDEST = 'OLDEST',
    PRICE_ASC = 'PRICE_ASC',
    PRICE_DESC = 'PRICE_DESC',
    REFUND_PRICE_ASC = 'REFUND_PRICE_ASC',
    REFUND_PRICE_DESC = 'REFUND_PRICE_DESC',
}